name: build

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
        - os: macos-12
        - os: windows-2022
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Create Build Environment
      env:
        RUNNER_WORKSPACE: ${{ runner.workspace }}
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        ./vcpkg/bootstrap-vcpkg.sh
        cmake -E make_directory "${RUNNER_WORKSPACE}/build"

    - name: Enable Developer Command Prompt (Windows)
      if: matrix.os == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: |
        cmake "${GITHUB_WORKSPACE}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          "-DCMAKE_TOOLCHAIN_FILE=${GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Upload Build Artifacts (Windows)
      uses: actions/upload-artifact@v4
      with:
          name: triton_bn_win64
          path: ${{ runner.workspace }}\build\*.dll

    - name: Upload Build Artifacts (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
          name: triton_bn_ubuntu2204
          path: ${{ runner.workspace }}/build/*.so

    - name: Upload Build Artifacts (MacOS)
      if: matrix.os == 'macos-12'
      uses: actions/upload-artifact@v4
      with:
          name: triton_bn_macOS
          path: ${{ runner.workspace }}/build/*.dylib
